platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

def flutter_root
  path = File.expand_path('Flutter/Generated.xcconfig', __dir__)
  File.foreach(path) do |line|
    match = line.match(/FLUTTER_ROOT\=(.*)/)
    return match[1].strip if match
  end
  raise 'Run flutter pub get first'
end
require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  pod 'crosstransfer_native', :path => 'native'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
